<?php
/**
 * TL_ROOT/system/modules/autolink/languages/fr/modules.php 
 * 
 * TYPOlight extension: autolink 2.3.3 stable 
 * French translation file 
 * 
 * Copyright : © 2009-2010 Andreas Schempp 
 * License   : LGPL 
 * Author    : Andreas Schempp (andreas.schempp), http://www.iserv.ch/ 
 * Translator: Cyril Ponce (cyril), http://www.typolight.fr 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['autolink']['0'] = "Liens automatiques";
 
?>
